// Copyright (c) 2019-2026 Provable Inc.
// This file is part of the snarkVM library.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::{
    env,
    ffi::OsStr,
    fs::{self, File},
    io::{self, BufRead, BufReader, Read, Write},
    path::{Path, PathBuf},
    process::Command,
    str::{self, FromStr},
};

use walkdir::WalkDir;

// The following license text that should be present at the beginning of every source file.
const EXPECTED_LICENSE_TEXT: &[u8] = include_bytes!(".resources/license_header");

// The following directories will be excluded from the license scan.
const DIRS_TO_SKIP: [&str; 5] = [".cargo", ".circleci", ".git", ".github", "target"];

// The name of the folder containing autogenerated files for dev/CI use.
const GENERATED_FILES_FOLDER: &str = ".generated_assets";

#[derive(Clone, Copy, PartialEq, Eq)]
enum ImportOfInterest {
    Locktick,
    ParkingLot,
    Tokio,
}

fn check_locktick_imports<P: AsRef<Path>>(path: P) {
    let mut iter = WalkDir::new(path).into_iter();
    while let Some(entry) = iter.next() {
        let entry = entry.unwrap();
        let entry_type = entry.file_type();

        // Skip the specified directories.
        if entry_type.is_dir() && DIRS_TO_SKIP.contains(&entry.file_name().to_str().unwrap_or("")) {
            iter.skip_current_dir();

            continue;
        }

        let path = entry.path();

        // Ignore non-rs
        if path.extension() != Some(OsStr::new("rs")) {
            continue;
        }

        // Read the entire file.
        let file = fs::read_to_string(path).unwrap();

        // Prepare a filtered line iterator.
        let lines = file
            .lines()
            .filter(|l| !l.is_empty()) // Ignore empty lines.
            .skip_while(|l| !l.starts_with("use")) // Skip the license etc.
            .take_while(|l| { // Process the section containing import statements.
                l.starts_with("use")
                    || l.starts_with("#[cfg")
                    || l.starts_with("//")
                    || *l == "};"
                    || l.starts_with(|c: char| c.is_ascii_whitespace())
            });

        // The currently processed import of interest.
        let mut import_of_interest: Option<ImportOfInterest> = None;
        // This value not being zero at the end of the imports suggests a missing locktick import.
        let mut lock_balance: i8 = 0;

        // Process the filtered lines.
        for line in lines {
            // Check if this is a lock-related import.
            if import_of_interest.is_none() {
                if line.starts_with("use locktick::") {
                    import_of_interest = Some(ImportOfInterest::Locktick);
                } else if line.starts_with("use parking_lot::") {
                    import_of_interest = Some(ImportOfInterest::ParkingLot);
                } else if line.starts_with("use tokio::") {
                    import_of_interest = Some(ImportOfInterest::Tokio);
                }
            }

            // Skip irrelevant imports.
            let Some(ioi) = import_of_interest else {
                continue;
            };

            // Modify the lock balance based on the type of the relevant import.
            if [ImportOfInterest::ParkingLot, ImportOfInterest::Tokio].contains(&ioi) {
                if line.contains("Mutex") {
                    lock_balance += 1;
                }
                if line.contains("RwLock") {
                    lock_balance += 1;
                }
            } else if ioi == ImportOfInterest::Locktick {
                // Use `matches` instead of just `contains` here, as more than a single
                // lock type entry is possible in a locktick import.
                for _hit in line.matches("Mutex") {
                    lock_balance -= 1;
                }
                for _hit in line.matches("RwLock") {
                    lock_balance -= 1;
                }
                // A correction in case of the `use tokio::Mutex as TMutex` convention.
                if line.contains("TMutex") {
                    lock_balance += 1;
                }
            }

            // Register the end of an import statement.
            if line.ends_with(";") {
                import_of_interest = None;
            }
        }

        // If the file has a lock import "imbalance", print it out and increment the counter.
        assert!(
            lock_balance == 0,
            "The locks in \"{}\" don't seem to have `locktick` counterparts!",
            entry.path().display()
        );
    }
}

fn check_file_licenses<P: AsRef<Path>>(path: P) {
    let path = path.as_ref();

    // Perform the license year check if on Linux.
    if cfg!(target_os = "linux") {
        // Get the current year from the OS
        let os_year = Command::new("date")
            .arg("+%Y") // ask only for the year
            .output()
            .expect("Failed to execute 'date' command");
        let current_year = str::from_utf8(&os_year.stdout).expect("Date output was not valid UTF-8").trim();

        // Check if the end of the year range in the license matches the OS year.
        let license_year = str::from_utf8(&EXPECTED_LICENSE_TEXT[22..][..4]).unwrap();
        assert_eq!(license_year, current_year, "The license year doesn't match the current OS year");
    }

    let mut iter = WalkDir::new(path).into_iter();
    while let Some(entry) = iter.next() {
        let entry = entry.unwrap();
        let entry_type = entry.file_type();

        // Skip the specified directories.
        if entry_type.is_dir() && DIRS_TO_SKIP.contains(&entry.file_name().to_str().unwrap_or("")) {
            iter.skip_current_dir();

            continue;
        }

        // Check all files with the ".rs" extension.
        if entry_type.is_file() && entry.file_name().to_str().unwrap_or("").ends_with(".rs") {
            let file = File::open(entry.path()).unwrap();
            let mut contents = Vec::with_capacity(EXPECTED_LICENSE_TEXT.len());
            file.take(EXPECTED_LICENSE_TEXT.len() as u64).read_to_end(&mut contents).unwrap();

            assert!(
                contents == EXPECTED_LICENSE_TEXT,
                "The license in \"{}\" is either missing or it doesn't match the expected string!",
                entry.path().display()
            );
        }
    }
}

fn generate_utility_files() {
    // Create the destination folder if missing.
    let project_path = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let mut generated_path = project_path.clone();
    generated_path.push(GENERATED_FILES_FOLDER);
    match fs::create_dir(&generated_path) {
        Ok(_) => {}
        Err(e) if e.kind() == io::ErrorKind::AlreadyExists => {}
        Err(e) => {
            panic!("Couldn't create the generated assets folder: {e}");
        }
    };

    // Store the number of consensus versions.
    let num_consensus_versions = get_num_consensus_versions();
    let mut file_path = generated_path;
    file_path.push("num_consensus_heights");
    let mut num_consensus_heights_file =
        File::create(&file_path).expect("Couldn't create the num_consensus_heights file");
    writeln!(num_consensus_heights_file, "{num_consensus_versions}")
        .expect("Couldn't write to the num_consensus_heights file");
}

fn get_num_consensus_versions() -> u32 {
    // Prepare the path containing the relevant source file.
    let mut consensus_heights_path = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    consensus_heights_path.extend(["console", "network", "src", "consensus_heights.rs"]);

    // Rerun the build script if the file changes.
    println!("cargo:rerun-if-changed={}", consensus_heights_path.display());

    // Open the source file and prepare to process it line-by-line.
    let consensus_heights_file =
        File::open(&consensus_heights_path).expect("Couldn't find the source file with consensus heights");
    let consensus_heights_reader = BufReader::new(consensus_heights_file);
    let mut line_iter = consensus_heights_reader.lines();

    // Find the location of the ConsensusVersion enum.
    line_iter.by_ref().find(|line| {
        line.as_ref().expect("Can't process the consensus heights file").contains("pub enum ConsensusVersion")
    });

    // Traverse the list of variants.
    let mut last_consensus_version = 0;
    for line in line_iter {
        let line = line.expect("Can't process the consensus heights file");
        // Split by whitespaces.
        let trimmed = line.trim();
        let mut parts = trimmed.split_whitespace();
        // Skip empty lines.
        let Some(variant) = parts.next() else {
            break;
        };

        // Expect a "VN = N," format
        if variant.starts_with("V") && parts.next() == Some("=") {
            let consensus_version = parts.next().expect("Unexpected consensus version enum format");
            let consensus_version = consensus_version.trim_end_matches(",");
            last_consensus_version = u32::from_str(consensus_version).expect("Unexpected consensus version encoding");
        } else if line == "}" {
            break;
        } else {
            continue;
        }
    }

    last_consensus_version
}

// The build script; it currently only checks the licenses.
fn main() {
    // Check licenses in the current folder.
    check_file_licenses(".");
    // Ensure that lock imports have locktick counterparts.
    check_locktick_imports(".");
    // Generate some dev/CI files.
    generate_utility_files();
}
