// Copyright (c) 2019-2026 Provable Inc.
// This file is part of the snarkVM library.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:

// http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::matches_type;

use super::*;

impl<N: Network> StackTrait<N> for Stack<N> {
    /// Checks that the given value matches the layout of the value type.
    fn matches_value_type(&self, value: &Value<N>, value_type: &ValueType<N>) -> Result<()> {
        // Ensure the value matches the declared value type in the register.
        match (value, value_type) {
            (Value::Plaintext(plaintext), ValueType::Constant(plaintext_type))
            | (Value::Plaintext(plaintext), ValueType::Public(plaintext_type))
            | (Value::Plaintext(plaintext), ValueType::Private(plaintext_type)) => {
                self.matches_plaintext(plaintext, plaintext_type)
            }
            (Value::Record(record), ValueType::Record(record_name)) => self.matches_record(record, record_name),
            (Value::Record(record), ValueType::ExternalRecord(locator)) => {
                self.matches_external_record(record, locator)
            }
            (Value::Future(future), ValueType::Future(locator)) => self.matches_future(future, locator),
            (Value::DynamicRecord(_), ValueType::DynamicRecord) => Ok(()),
            (Value::DynamicFuture(_), ValueType::DynamicFuture) => Ok(()),
            (value, _) => bail!("A value '{value}' does not match its declared value type '{value_type}'"),
        }
    }

    // The following type-matching methods fall back to the private functions generated by the
    // matches_type! macro later in this file and share the same functionality as their circuit
    // counterparts generated with the same macro.

    /// Checks that the given stack value matches the layout of the register type.
    fn matches_register_type(&self, stack_value: &Value<N>, register_type: &RegisterType<N>) -> Result<()> {
        console_matches_register_type(self, stack_value, register_type)
    }

    /// Checks that the given record matches the layout of the external record type.
    fn matches_external_record(&self, record: &Record<N, Plaintext<N>>, locator: &Locator<N>) -> Result<()> {
        console_matches_external_record(self, record, locator)
    }

    /// Checks that the given record matches the layout of the record type.
    fn matches_record(&self, record: &Record<N, Plaintext<N>>, record_name: &Identifier<N>) -> Result<()> {
        console_matches_record(self, record, record_name)
    }

    /// Checks that the given plaintext matches the layout of the plaintext type.
    fn matches_plaintext(&self, plaintext: &Plaintext<N>, plaintext_type: &PlaintextType<N>) -> Result<()> {
        console_matches_plaintext(self, plaintext, plaintext_type)
    }

    /// Checks that the given future matches the layout of the future type.
    fn matches_future(&self, future: &Future<N>, locator: &Locator<N>) -> Result<()> {
        console_matches_future(self, future, locator)
    }

    /// Returns `true` if the proving key for the given name exists.
    /// The name can be a function name or a record name (for translation keys).
    fn contains_proving_key(&self, function_or_record_name: &Identifier<N>) -> bool {
        self.proving_keys.read().contains_key(function_or_record_name)
    }

    /// Returns the proving key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn get_proving_key(&self, function_or_record_name: &Identifier<N>) -> Result<ProvingKey<N>> {
        // If the program is 'credits.aleo', try to load the proving key, if it does not exist.
        self.try_insert_credits_function_proving_key(function_or_record_name)?;
        // Return the proving key, if it exists.
        match self.proving_keys.read().get(function_or_record_name) {
            Some(pk) => Ok(pk.clone()),
            None => bail!("Proving key not found for: {}/{}", self.program.id(), function_or_record_name),
        }
    }

    /// Inserts the given proving key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn insert_proving_key(&self, function_or_record_name: &Identifier<N>, proving_key: ProvingKey<N>) -> Result<()> {
        // Ensure the name exists in the program as a function or record.
        ensure!(
            self.program.contains_function(function_or_record_name)
                || self.program.contains_record(function_or_record_name),
            "'{function_or_record_name}' does not exist as a function or record in program '{}'.",
            self.program.id()
        );
        // Insert the proving key.
        self.proving_keys.write().insert(*function_or_record_name, proving_key);
        Ok(())
    }

    /// Removes the proving key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn remove_proving_key(&self, function_or_record_name: &Identifier<N>) {
        self.proving_keys.write().shift_remove(function_or_record_name);
    }

    /// Returns `true` if the verifying key for the given name exists.
    /// The name can be a function name or a record name (for translation keys).
    fn contains_verifying_key(&self, function_or_record_name: &Identifier<N>) -> bool {
        self.verifying_keys.read().contains_key(function_or_record_name)
    }

    /// Returns the verifying key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn get_verifying_key(&self, function_or_record_name: &Identifier<N>) -> Result<VerifyingKey<N>> {
        // Return the verifying key, if it exists.
        match self.verifying_keys.read().get(function_or_record_name) {
            Some(vk) => Ok(vk.clone()),
            None => bail!("Verifying key not found for: {}/{}", self.program.id(), function_or_record_name),
        }
    }

    /// Inserts the given verifying key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn insert_verifying_key(
        &self,
        function_or_record_name: &Identifier<N>,
        verifying_key: VerifyingKey<N>,
    ) -> Result<()> {
        // Ensure the name exists in the program as a function or record.
        ensure!(
            self.program.contains_function(function_or_record_name)
                || self.program.contains_record(function_or_record_name),
            "'{function_or_record_name}' does not exist as a function or record in program '{}'.",
            self.program.id()
        );
        // Insert the verifying key.
        self.verifying_keys.write().insert(*function_or_record_name, verifying_key);
        Ok(())
    }

    /// Removes the verifying key for the given name.
    /// The name can be a function name or a record name (for translation keys).
    fn remove_verifying_key(&self, function_or_record_name: &Identifier<N>) {
        self.verifying_keys.write().shift_remove(function_or_record_name);
    }

    /// Returns the program.
    fn program(&self) -> &Program<N> {
        &self.program
    }

    /// Returns the program ID.
    fn program_id(&self) -> &ProgramID<N> {
        self.program.id()
    }

    /// Returns the program address.
    fn program_address(&self) -> &Address<N> {
        &self.program_address
    }

    /// Returns the program checksum.
    fn program_checksum(&self) -> &[U8<N>; 32] {
        &self.program_checksum
    }

    /// Returns the program checksum as a field element.
    #[inline]
    fn program_checksum_as_field(&self) -> Result<Field<N>> {
        // Get the bits of the program checksum, truncated to the field size.
        let bits = self
            .program_checksum
            .iter()
            .flat_map(|byte| byte.to_bits_le())
            .take(Field::<N>::SIZE_IN_DATA_BITS)
            .collect::<Vec<_>>();
        // Return the field element from the bits.
        Field::from_bits_le(&bits)
    }

    /// Returns the checksum of the program component (function, closure, or view) with the given name.
    fn component_checksum(&self, name: &Identifier<N>) -> Result<&[U8<N>; 32]> {
        self.component_checksums
            .get(name)
            .ok_or_else(|| anyhow!("'{name}' is not a function, closure, or view in '{}'.", self.program_id()))
    }

    /// Returns the program edition.
    #[inline]
    fn program_edition(&self) -> U16<N> {
        self.program_edition
    }

    /// Returns the number of amendments for the current program edition.
    #[inline]
    fn program_amendment_count(&self) -> u64 {
        self.program_amendment_count
    }

    /// Sets the number of amendments for the current program edition.
    fn set_program_amendment_count(&mut self, program_amendment_count: u64) {
        self.program_amendment_count = program_amendment_count;
    }

    /// Returns the program owner.
    #[inline]
    fn program_owner(&self) -> &Option<Address<N>> {
        &self.program_owner
    }

    /// Sets the program owner.
    /// The program owner should only be set for programs that are deployed after `ConsensusVersion::V9` is active.
    fn set_program_owner(&mut self, program_owner: Option<Address<N>>) {
        self.program_owner = program_owner;
    }

    /// Returns the external stack for the given program ID.
    ///
    /// Attention - this function is used to check the existence of the external program.
    /// Developers should explicitly handle the error case so as to not default to the main program.
    fn get_external_stack(&self, program_id: &ProgramID<N>) -> Result<Arc<Stack<N>>> {
        // Check that the program ID is not itself.
        ensure!(
            program_id != self.program.id(),
            "Attempted to get the main program '{program_id}' as an external program."
        );
        // Check that the program ID is imported by the program.
        ensure!(self.program.contains_import(program_id), "External program '{program_id}' is not imported.");
        // Upgrade the weak reference to the process-level stack map and retrieve the external stack.
        self.stacks
            .upgrade()
            .ok_or_else(|| anyhow!("Process-level stack map does not exist"))?
            .read()
            .get(program_id)
            .cloned()
            .ok_or_else(|| anyhow!("External stack for '{program_id}' does not exist"))
    }

    /// Returns the stack for the given program ID.
    ///
    /// Attention - this function does **NOT** check that the program is imported by the current program.
    /// This function is only to be used for resolution during dynamic dispatch.
    fn get_stack_global(&self, program_id: &ProgramID<N>) -> Result<Arc<Stack<N>>> {
        // Upgrade the weak reference to the process-level stack map and retrieve the external stack.
        self.stacks
            .upgrade()
            .ok_or_else(|| anyhow!("Process-level stack map does not exist"))?
            .read()
            .get(program_id)
            .cloned()
            .ok_or_else(|| anyhow!("External stack for '{program_id}' does not exist"))
    }

    /// Returns the function with the given function name.
    fn get_function(&self, function_name: &Identifier<N>) -> Result<Function<N>> {
        self.program.get_function(function_name)
    }

    /// Returns a reference to the function with the given function name.
    fn get_function_ref(&self, function_name: &Identifier<N>) -> Result<&Function<N>> {
        self.program.get_function_ref(function_name)
    }

    /// Returns the minimum number of calls for the given function name.
    /// In the case where there are no dynamic calls, this is equivalent to the total number of calls.
    fn get_minimum_number_of_calls(&self, function_name: &Identifier<N>) -> Result<usize> {
        // Initialize the base number of calls.
        let mut num_calls = 1;
        // Initialize a queue of functions to check.
        let mut queue = vec![(StackRef::Internal(self), *function_name)];
        // Iterate over the queue.
        while let Some((stack_ref, function_name)) = queue.pop() {
            // Ensure that the number of calls does not exceed the maximum.
            // Note that one transition is reserved for the fee.
            ensure!(
                num_calls < Transaction::<N>::MAX_TRANSITIONS,
                "Number of calls must be less than '{}'",
                Transaction::<N>::MAX_TRANSITIONS
            );
            // Determine the number of calls for the function.
            for instruction in stack_ref.get_function_ref(&function_name)?.instructions() {
                match instruction {
                    Instruction::Call(call) => {
                        // Determine if this is a function call.
                        if call.is_function_call(&*stack_ref)? {
                            // Increment the number of calls.
                            num_calls += 1;
                            // Add the function to the queue.
                            match call.operator() {
                                CallOperator::Locator(locator) => {
                                    // If the locator matches the program ID of the provided stack, use it directly.
                                    // Otherwise, retrieve the external stack.
                                    let stack = if locator.program_id() == self.program().id() {
                                        StackRef::Internal(self)
                                    } else {
                                        StackRef::External(stack_ref.get_external_stack(locator.program_id())?)
                                    };
                                    queue.push((stack, *locator.resource()));
                                }
                                CallOperator::Resource(resource) => {
                                    queue.push((stack_ref.clone(), *resource));
                                }
                            }
                        }
                    }
                    Instruction::CallDynamic(_) => {
                        // Increment the number of calls.
                        num_calls += 1
                    }
                    _ => (),
                }
            }
        }
        // Return the number of calls.
        Ok(num_calls)
    }

    /// Returns whether or not a function has a dynamic call in its execution.
    fn contains_dynamic_call(&self, function_name: &Identifier<N>) -> Result<bool> {
        // Initialize the base number of calls.
        let mut num_calls = 1;
        // Initialize a queue of functions to check.
        let mut queue = vec![(StackRef::Internal(self), *function_name)];
        // Iterate over the queue.
        while let Some((stack_ref, function_name)) = queue.pop() {
            // Ensure that the number of calls does not exceed the maximum.
            // Note that one transition is reserved for the fee.
            ensure!(
                num_calls < Transaction::<N>::MAX_TRANSITIONS,
                "Number of calls must be less than '{}'",
                Transaction::<N>::MAX_TRANSITIONS
            );
            // Determine the number of calls for the function.
            for instruction in stack_ref.get_function_ref(&function_name)?.instructions() {
                match instruction {
                    Instruction::Call(call) => {
                        // Determine if this is a function call.
                        if call.is_function_call(&*stack_ref)? {
                            // Increment by the number of calls.
                            num_calls += 1;
                            // Add the function to the queue.
                            match call.operator() {
                                CallOperator::Locator(locator) => {
                                    // If the locator matches the program ID of the provided stack, use it directly.
                                    // Otherwise, retrieve the external stack.
                                    let stack = if locator.program_id() == self.program().id() {
                                        StackRef::Internal(self)
                                    } else {
                                        StackRef::External(stack_ref.get_external_stack(locator.program_id())?)
                                    };
                                    queue.push((stack, *locator.resource()));
                                }
                                CallOperator::Resource(resource) => {
                                    queue.push((stack_ref.clone(), *resource));
                                }
                            }
                        }
                    }
                    Instruction::CallDynamic(_) => return Ok(true),
                    _ => (),
                }
            }
        }
        // No dynamic calls have been found.
        Ok(false)
    }

    /// Returns a value for the given register type.
    fn sample_value<R: Rng + CryptoRng>(
        &self,
        burner_address: &Address<N>,
        register_type: &RegisterType<N>,
        rng: &mut R,
    ) -> Result<Value<N>> {
        match register_type {
            RegisterType::Plaintext(plaintext_type) => {
                Ok(Value::Plaintext(self.sample_plaintext(plaintext_type, rng)?))
            }
            RegisterType::Record(record_name) => {
                Ok(Value::Record(self.sample_record(burner_address, record_name, Group::rand(rng), rng)?))
            }
            RegisterType::ExternalRecord(locator) => {
                // Retrieve the external stack.
                let stack = self.get_external_stack(locator.program_id())?;
                // Sample the output.
                Ok(Value::Record(stack.sample_record(burner_address, locator.resource(), Group::rand(rng), rng)?))
            }
            RegisterType::Future(locator) => Ok(Value::Future(self.sample_future(locator, rng)?)),
            RegisterType::DynamicRecord => Ok(Value::DynamicRecord(self.sample_dynamic_record(rng)?)),
            RegisterType::DynamicFuture => Ok(Value::DynamicFuture(self.sample_dynamic_future(rng)?)),
        }
    }

    /// Returns a record for the given record name, with the given burner address and nonce.
    fn sample_record<R: Rng + CryptoRng>(
        &self,
        burner_address: &Address<N>,
        record_name: &Identifier<N>,
        nonce: Group<N>,
        rng: &mut R,
    ) -> Result<Record<N, Plaintext<N>>> {
        // Sample a record.
        let record = self.sample_record_internal(burner_address, record_name, nonce, 0, rng)?;
        // Ensure the record matches the value type.
        self.matches_record(&record, record_name)?;
        // Return the record.
        Ok(record)
    }

    /// Returns a record for the given record name, deriving the nonce from tvk and index.
    fn sample_record_using_tvk<R: Rng + CryptoRng>(
        &self,
        burner_address: &Address<N>,
        record_name: &Identifier<N>,
        tvk: Field<N>,
        index: Field<N>,
        rng: &mut R,
    ) -> Result<Record<N, Plaintext<N>>> {
        // Compute the randomizer.
        let randomizer = N::hash_to_scalar_psd2(&[tvk, index])?;
        // Construct the record nonce from that randomizer.
        let record_nonce = N::g_scalar_multiply(&randomizer);
        // Sample the record with that nonce.
        self.sample_record(burner_address, record_name, record_nonce, rng)
    }

    fn evaluate_view(
        &self,
        state: FinalizeGlobalState,
        store: &dyn FinalizeStoreTrait<N>,
        view_name: &Identifier<N>,
        inputs: Vec<Value<N>>,
    ) -> Result<Vec<Value<N>>> {
        crate::view::evaluate_view_inner(state, store, self, view_name, inputs)
    }
}

// This macro invocation generates the private functions which the public methods exposed by the
// StackTrait macro wrap around.
matches_type!(
    // Path to value types
    console::program,
    // Generics
    { <N: Network> },
    N,
    // Pass-through function, replaced by eject_value in some (limited) places in the circuit analogue.
    into,
    // Names of the private functions to be generated.
    console_matches_register_type,
    console_matches_external_record,
    console_matches_record,
    console_matches_plaintext,
    console_matches_future,
    console_matches_record_internal,
    console_matches_entry_internal,
    console_matches_plaintext_internal,
    console_matches_future_internal,
);

#[cfg(test)]
mod tests {
    use super::*;
    use console::network::MainnetV0;
    use snarkvm_synthesizer_program::Program;

    type CurrentNetwork = MainnetV0;

    // This test verifies that `contains_dynamic_call` returns `false` for a function
    // that contains only static `call` instructions (no `call.dynamic`).
    #[test]
    fn test_contains_dynamic_call_with_static_calls() {
        // `Process::load` always includes `credits.aleo`, which has no dynamic calls.
        let process = Process::<CurrentNetwork>::load().unwrap();
        let stack = process.get_stack("credits.aleo").unwrap();
        // `transfer_public` uses only static operations — no `call.dynamic`.
        let function_name = Identifier::from_str("transfer_public").unwrap();
        assert!(!stack.contains_dynamic_call(&function_name).unwrap());
    }

    // This test verifies that `contains_dynamic_call` returns `true` for a function
    // that directly contains a `call.dynamic` instruction.
    #[test]
    fn test_contains_dynamic_call_with_dynamic_calls() {
        // Define a program with a function that issues a bare `call.dynamic` (no inputs or outputs).
        let program = Program::<CurrentNetwork>::from_str(
            r"
program dynamic_test.aleo;

function dynamic_func:
    input r0 as field.public;
    input r1 as field.public;
    input r2 as field.public;
    call.dynamic r0 r1 r2;",
        )
        .unwrap();
        // Add the program to a fresh process (no deployment needed for stack inspection).
        let process = Process::<CurrentNetwork>::load().unwrap();
        process.lock().add_program(&program).unwrap();
        let stack = process.get_stack("dynamic_test.aleo").unwrap();
        // `dynamic_func` contains a `call.dynamic` instruction and must be detected.
        let function_name = Identifier::from_str("dynamic_func").unwrap();
        assert!(stack.contains_dynamic_call(&function_name).unwrap());
    }

    // This test verifies that `contains_dynamic_call` returns `true` for a function that
    // transitively reaches a `call.dynamic` via a static external call.
    #[test]
    fn test_contains_dynamic_call_transitive() {
        // Define a helper program whose function issues `call.dynamic`.
        let helper_program = Program::<CurrentNetwork>::from_str(
            r"
program helper.aleo;

function dynamic_helper:
    input r0 as field.public;
    input r1 as field.public;
    input r2 as field.public;
    call.dynamic r0 r1 r2;",
        )
        .unwrap();
        // Define a caller program that statically calls `helper.aleo/dynamic_helper`.
        let caller_program = Program::<CurrentNetwork>::from_str(
            r"
import helper.aleo;

program caller.aleo;

function caller_func:
    input r0 as field.public;
    input r1 as field.public;
    input r2 as field.public;
    call helper.aleo/dynamic_helper r0 r1 r2;",
        )
        .unwrap();
        // Add programs in dependency order: helper first, then caller.
        let process = Process::<CurrentNetwork>::load().unwrap();
        process.lock().add_program(&helper_program).unwrap();
        process.lock().add_program(&caller_program).unwrap();
        let stack = process.get_stack("caller.aleo").unwrap();
        // `caller_func` transitively reaches `call.dynamic` via `helper.aleo/dynamic_helper`.
        let function_name = Identifier::from_str("caller_func").unwrap();
        assert!(stack.contains_dynamic_call(&function_name).unwrap());
    }

    // This test verifies that `console_matches_register_type` accepts every value whose layout
    // matches its register type and rejects every mismatched combination.
    #[test]
    fn test_console_matches_register_type() {
        let program_id = "test_matcher.aleo";

        // A program that defines the internal record, self-referential future, and external import
        // needed to exercise every `RegisterType` variant. This is necessary as ExternalRecords and
        // Records have different RegisterType but the same Value variant (if they refer to the same
        // static-record type).
        let program_str = r"
            import credits.aleo;
    
            program test_matcher.aleo;
    
            record token:
                owner as address.private;
                amount as u64.private;
    
            function make_future:
                input r0 as u64.public;
                async make_future r0 into r1;
                output r1 as test_matcher.aleo/make_future.future;
    
            finalize make_future:
                input r0 as u64.public;
                add r0 r0 into r1;
            ";

        let owner: &str = "aleo1d5hg2z3ma00382pngntdp68e74zv54jdxy249qhaujhks9c72yrs33ddah";

        // `(register type, value)` pairs covering every `RegisterType` variant. Each value matches its
        // own register type and no other register type in the list.
        let cases = vec![
            ("boolean", "true".to_string()),
            ("field", "1field".to_string()),
            ("group", "0group".to_string()),
            ("scalar", "1scalar".to_string()),
            ("u8", "1u8".to_string()),
            ("u16", "1u16".to_string()),
            ("u32", "1u32".to_string()),
            ("u64", "1u64".to_string()),
            ("u128", "1u128".to_string()),
            ("i8", "1i8".to_string()),
            ("i16", "1i16".to_string()),
            ("i32", "1i32".to_string()),
            ("i64", "1i64".to_string()),
            ("i128", "1i128".to_string()),
            ("[u8; 3u32]", "[1u8, 2u8, 3u8]".to_string()),
            // A static Record. `amount` distinguishes its layout from the `credits` record, used for
            // the ExternalRecord case.
            (
                "token.record",
                format!(
                    "{{ owner: {owner}.private, amount: 5u64.private, _nonce: 0group.public, _version: 0u8.public }}"
                ),
            ),
            // An ExternalRecord. `microcredits` distinguishes its layout from that of the `token` record.
            (
                "credits.aleo/credits.record",
                format!(
                    "{{ owner: {owner}.private, microcredits: 5u64.private, _nonce: 0group.public, _version: 0u8.public }}"
                ),
            ),
            // A future whose program ID, function name, and argument match `make_future`.
            (
                "test_matcher.aleo/make_future.future",
                "{ program_id: test_matcher.aleo, function_name: make_future, arguments: [ 5u64 ] }".to_string(),
            ),
            ("dynamic.record", format!("{{ owner: {owner}, _root: 0field, _nonce: 0group, _version: 0u8 }}")),
            (
                "dynamic.future",
                "{ _program_id: credits.aleo, _function_name: transfer_public, _checksum: 0field }".to_string(),
            ),
        ];

        // Build a stack for a program that exercises every register type variant.
        let program = Program::<CurrentNetwork>::from_str(program_str).unwrap();
        let process = Process::<CurrentNetwork>::load().unwrap();
        process.lock().add_program(&program).unwrap();
        let stack = process.get_stack(program_id).unwrap();

        let types: Vec<_> = cases.iter().map(|(t, _)| RegisterType::<CurrentNetwork>::from_str(t).unwrap()).collect();
        let values: Vec<_> = cases.iter().map(|(_, v)| Value::<CurrentNetwork>::from_str(v).unwrap()).collect();

        // Every value matches its own register type (all correct combinations) and fails against
        // every other register type in the matrix (many incorrect combinations per type).
        for (i, value) in values.iter().enumerate() {
            for (j, register_type) in types.iter().enumerate() {
                let result = console_matches_register_type(&*stack, value, register_type);
                if i == j {
                    assert!(result.is_ok(), "expected '{}' to match '{}': {result:?}", cases[i].1, cases[j].0);
                } else {
                    assert!(result.is_err(), "expected '{}' to not match '{}'", cases[i].1, cases[j].0);
                }
            }
        }
    }
}
