name: CI - Console Tests

on:
  pull_request:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  RUST_MIN_STACK: 67108864

jobs:
  console:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console --profile ci

  console-account:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-account-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-account-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-account --profile ci

  console-algorithms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-algorithms-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-algorithms-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-algorithms --profile ci

  console-collections:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-collections-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-collections-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-collections --profile ci

  console-network:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-network-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-network-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-network --profile ci

  console-network-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-network-environment-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-network-environment-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-network-environment --profile ci

  console-program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-program-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-program-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-program --profile ci

  console-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types --profile ci

  console-types-address:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-address-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-address-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-address --profile ci

  console-types-boolean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-boolean-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-boolean-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-boolean --profile ci

  console-types-field:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-field-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-field-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-field --profile ci

  console-types-group:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-group-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-group-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-group --profile ci

  console-types-integers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-integers-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-integers-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-integers --profile ci

  console-types-scalar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-scalar-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-scalar-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-scalar --profile ci

  console-types-string:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang llvm-dev llvm lld pkg-config xz-utils make libssl-dev
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-console-types-string-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-console-types-string-
      - name: Install cargo-nextest
        run: cargo install cargo-nextest --locked --version 0.9.114
      - name: Run Tests
        run: cargo nextest run -p snarkvm-console-types-string --profile ci
